/* eslint-disable no-tabs */
module.exports = {
  content:
	'IODF     12 SYS1     LBI9MVS\nNUCLEUS  1\nNUCLST   00\nSYSCAT   MI9MC1123CSYS1.MCAT.VMI9MC1\nSYSPARM  00\nIEASYM   00\nPARMLIB  SYS1.LBI9.PARMLIB\nPARMLIB  SYS1.PARMLIB\nPARMLIB  SYS1.CA.PARMLIB\nPARMLIB  SYS1.IBM.PARMLIB\n'
};
